version: '3.8'

services:
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            - MYSQL_USER=test
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=root-secret
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=employees
        ports: 
            - "3306:3306"
        volumes:
            - ./tests/resources/employees.sql:/docker-entrypoint-initdb.d/employees.sql
        container_name: nck_test_mysql_db
        cap_add: 
            - SYS_NICE
    tests:
        build:
            context: .
            dockerfile: Dockerfile.test
        environment:
           - MYSQL_DATABASE=employees
           - MYSQL_HOST=db
           - MYSQL_PORT=3306
           - MYSQL_USER=test
           - MYSQL_PASSWORD=secret
           - PYTHONPATH=.
        depends_on:
            - db