FILE_NAMES = {
    "FILE_TYPE_INSERTION_ORDER": "InsertionOrders",
    "FILE_TYPE_CAMPAIGN": "Campaigns",
    "FILE_TYPE_MEDIA_PRODUCT": "MediaProducts",
    "FILE_TYPE_LINE_ITEM": "LineItems",
    "FILE_TYPE_AD_GROUP": "AdGroups",
    "FILE_TYPE_AD": "AdGroupAds"
}

FILE_TYPES = FILE_NAMES.keys()

FILTER_TYPES = [
    "FILTER_TYPE_UNSPECIFIED",
    "FILTER_TYPE_NONE",
    "FILTER_TYPE_ADVERTISER_ID",
    "FILTER_TYPE_CAMPAIGN_ID",
    "FILTER_TYPE_MEDIA_PRODUCT_ID",
    "FILTER_TYPE_INSERTION_ORDER_ID",
    "FILTER_TYPE_LINE_ITEM_ID"
]
